name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean Environment
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install

      - name: Fix Playwright Permissions
        run: chmod +x ./node_modules/.bin/playwright

      - name: Run Playwright Tests
        run: npx playwright test
